### ISSUE TITLE
#Enhance UI.

### ISSUE THREAD

**Issue by anish2210** [anish2210/iBlog#2]
Enhance the homepage UI

**Comment by surajb0710** [comment]
Can you please assign this issue to me?
Do you have any inputs on the UI design Or you are just looking for a nice UI? If you do not have anything specific, then I will look for a blog UI design and then will develop the UI accordingly. Also, I will ensure, it is mobile responsive, so you can assign issue 3 as well to me.

**Comment by anish2210** [comment]
Yeah It would be great if you to look for a UI design and develop it accordingly.

**Comment by surajb0710** [comment]
Just to update you, I am now trying to refine the responsiveness. I was not very happy with my earlier outcome, so redoing it to make it better.
