### ISSUE TITLE
Login url and create blog url throws 404 error when page is refreshed

### ISSUE THREAD

**Issue by surajb0710** [anish2210/iBlog#5]
Steps to Reproduce:
1. Access mentioned urls
2. Upon refreshing the page 404 error is visible

url : 
https://i-blogg.vercel.app/login
https://i-blogg.vercel.app/CreateBlog

Note : This issue is not visible on local

https://github.com/user-attachments/assets/c9c8f313-c256-40e5-b62c-1a0c719fb39d

**Comment by anish2210** [comment]
@surajb0710 would you like to work on it and resolve the issues?

**Comment by surajb0710** [comment]
Yes sure, I have raised the PR for this issue.
This change will require all the routes to be retested, I will be able to check it once the PR is merged.

**Comment by surajb0710** [comment]
Hi @anish2210 any issues with the PR?

**Comment by anish2210** [comment]
no brother, I was just busy with some other work... will be reviewing and merging it soon
